# Generated by Django 5.2.8 on 2025-12-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('internal', 'Internal Storage'), ('external', 'External Location'), ('receiving', 'Receiving Area'), ('shipping', 'Shipping Bay')], default='internal', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='structural',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
    ]
