# Generated by Django 5.2.8 on 2025-12-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_category_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='date',
            field=models.DateField(),
        ),
    ]
