# Generated by Django 5.2.8 on 2026-02-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_activity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='item',
            name='safety_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
