# Generated by Django 5.2.8 on 2026-02-25 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_item_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('score', models.FloatField(help_text='IsolationForest anomaly score (lower = more abnormal)')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_anomalies', to='inventory.item')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('item', 'date')},
            },
        ),
    ]
