# Generated by Django 5.2.8 on 2026-02-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_demandanomaly'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandanomaly',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandanomaly',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandanomaly',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
