# Generated by Django 5.2.8 on 2026-02-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_demandanomaly_dismissed_demandanomaly_dismissed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
