# Generated by Django 5.2.8 on 2026-02-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='weekly_reports',
            field=models.BooleanField(default=False),
        ),
    ]
