# Generated by Django 5.2.8 on 2026-02-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_userpreference_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='accent_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red'), ('orange', 'Orange'), ('pink', 'Pink')], default='blue', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='items_per_page',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10),
        ),
    ]
