# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='pcs', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes (not shown to customers)'),
        ),
    ]
