# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_add_item_barcode_uom_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='batch_code',
            field=models.CharField(blank=True, help_text='Batch or lot number for tracking', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('damaged', 'Damaged'), ('quarantine', 'Quarantine'), ('returned', 'Returned'), ('on_hold', 'On Hold')], default='OK', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Stock considered expired after this date', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR - Euro'), ('USD', 'USD - US Dollar'), ('GBP', 'GBP - British Pound')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='packaging',
            field=models.CharField(blank=True, help_text='How this item is packaged (e.g. box, pallet)', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to datasheet, product page, etc.', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_numbers',
            field=models.TextField(blank=True, help_text='Serial numbers (one per line)'),
        ),
        migrations.AddField(
            model_name='item',
            name='delete_on_deplete',
            field=models.BooleanField(default=False, help_text='Archive this item when stock reaches zero'),
        ),
    ]
