# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_location_children_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, help_text='Short code e.g. A-01, B-12', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, help_text='Location photo or diagram', null=True, upload_to='locations/'),
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address (for external locations)'),
        ),
        migrations.AddField(
            model_name='location',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode for scanning', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes (not shown externally)'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
