# Generated by Django 5.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_location_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_location',
            field=models.ForeignKey(
                blank=True,
                help_text='Location goods are shipped from (for sale orders)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders_shipped_from',
                to='inventory.location',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='receiving_location',
            field=models.ForeignKey(
                blank=True,
                help_text='Location goods are received at (for purchase orders)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders_received_at',
                to='inventory.location',
            ),
        ),
    ]
