# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_order_shipping_receiving_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Maximum units this location can hold (for utilisation tracking)',
                null=True,
            ),
        ),
    ]
