# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_location_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS latitude (e.g. 53.349805)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS longitude (e.g. -6.260310)",
                max_digits=9,
                null=True,
            ),
        ),
    ]
