# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_location_latitude_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Order reference e.g. PO0020, SO0029",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="party_reference",
            field=models.CharField(
                blank=True,
                help_text="Supplier/customer order reference code",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Expected delivery date. Order overdue after this.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="external_link",
            field=models.URLField(blank=True),
        ),
    ]
