# Generated by Django 5.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_add_order_metadata_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="order_lines", to="inventory.item")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.order")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(
            lambda apps, schema_editor: _migrate_order_lines(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(model_name="order", name="item"),
        migrations.RemoveField(model_name="order", name="quantity"),
        migrations.RemoveField(model_name="order", name="unit_price"),
    ]


def _migrate_order_lines(apps, schema_editor):
    Order = apps.get_model("inventory", "Order")
    OrderLine = apps.get_model("inventory", "OrderLine")
    for order in Order.objects.all():
        if order.item_id:
            OrderLine.objects.create(
                order=order,
                item_id=order.item_id,
                quantity=order.quantity,
                unit_price=order.unit_price,
            )
