# Generated by Django 5.2.8 on 2026-03-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_recommendation_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='inventory_r_recomme_364c46_idx',
            old_name='inventory_r_recomme_56b0c8_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='inventory_r_item_id_9e16fe_idx',
            old_name='inventory_r_item_id_aa3b4d_idx',
        ),
    ]
