# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0032_rename_inventory_r_recomme_56b0c8_idx_inventory_r_recomme_364c46_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="description",
            field=models.TextField(blank=True, help_text="Description of the company"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="website",
            field=models.URLField(blank=True, help_text="Company website URL"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="image",
            field=models.ImageField(blank=True, help_text="Company logo or image", null=True, upload_to="suppliers/"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="currency",
            field=models.CharField(blank=True, help_text="Default currency e.g. EUR, USD", max_length=10),
        ),
        migrations.AddField(
            model_name="supplier",
            name="tax_id",
            field=models.CharField(blank=True, help_text="Company Tax ID", max_length=50),
        ),
        migrations.AddField(
            model_name="supplier",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal notes"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="client",
            name="description",
            field=models.TextField(blank=True, help_text="Description of the company"),
        ),
        migrations.AddField(
            model_name="client",
            name="website",
            field=models.URLField(blank=True, help_text="Company website URL"),
        ),
        migrations.AddField(
            model_name="client",
            name="image",
            field=models.ImageField(blank=True, help_text="Company logo or image", null=True, upload_to="customers/"),
        ),
        migrations.AddField(
            model_name="client",
            name="currency",
            field=models.CharField(blank=True, help_text="Default currency e.g. EUR, USD", max_length=10),
        ),
        migrations.AddField(
            model_name="client",
            name="tax_id",
            field=models.CharField(blank=True, help_text="Company Tax ID", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal notes"),
        ),
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
