# Generated by Django 6.0.3 on 2026-04-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_userpreference_theme_default_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Shown in the header menu and on your profile.', null=True, upload_to='profile_avatars/'),
        ),
    ]
