# Generated by Django 6.0.3 on 2026-04-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('item_create', 'New item'), ('item_update', 'Item updated'), ('item_adjust', 'Quantity'), ('item_archive', 'Archived'), ('item_unarchive', 'Unarchived'), ('item_delete', 'Deleted'), ('item_hard_delete', 'Permanent delete'), ('item_auto_archive', 'Auto-archived'), ('order_stock', 'Order & stock'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
